# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: city_api
    ports:
      - "5432:5432"
    volumes:
      - postegre_data:/data/db
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postegre_data:
