services:
  api:
    build:
      context: ./city-api
      target: dev
    env_file:
      - city-api/.env
    restart: always
    ports:
      - "2022:2022"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      # POSTGRES_USER: postgres
      POSTGRES_DB: city_api
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/

volumes:
  data:
