{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
  name: city
  namespace: {{ .Values.global.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: city
            port: 
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}   
    secretName: {{ .Values.ingress.hostname }} 
{{- end -}}