apiVersion: v1
kind: Secret
metadata:
  name: db
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  # postgres://userdemo:password1@127.0.0.1:5432/portal-demo?sslmode=disable  
  connectionstring: cG9zdGdyZXM6Ly91c2VyZGVtbzpwYXNzd29yZDFAMTI3LjAuMC4xOjU0MzIvcG9ydGFsLWRlbW8/c3NsbW9kZT1kaXNhYmxl

  