---
apiVersion: v1
kind: Service
metadata:
  name: city
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    {{ template "city.label" . }}
  ports:
  - name: http
    port: 80
    protocol: "TCP"
    targetPort: custom
  type: ClusterIP
...